version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dcuk-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dcuk-assessment
    volumes:
      - mongodb_data:/data/db
    networks:
      - dcuk-network

volumes:
  mongodb_data:
    driver: local

networks:
  dcuk-network:
    driver: bridge

